name: build

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: install
        run: npm i

      - name: build
        run: npm run build

      - name: setup SSH keys and known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.ID_RSA }}"
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: clone repository
        run: git clone git@github.com:harrisoff/harrisoff.github.io.git
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

      - name: delete old files
        run: cd harrisoff.github.io&&rm -rf sitar-admin sitar-admin.html

      - name: add new files
        run: cd harrisoff.github.io&&cp ../dist/sitar-admin.html sitar-admin.html&&cp -r ../dist/sitar-admin sitar-admin

      - name: git config
        run: git config --global user.email "john@smith.kyon"&&git config --global user.name "harrisoff"

      - name: update repo
        run: cp deploy.sh harrisoff.github.io/a.sh&&cd harrisoff.github.io&&chmod 744 a.sh&&./a.sh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock